version: '2'
services:
  hyper-hdr:
    container_name: hyper-hdr
    hostname: hyper-hdr
    image: nocturno/hyper-hdr:latest
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000

    volumes:
      - /home/pi/containersdata/hyperhdr:/config
    restart: unless-stopped
    
  dozzle-agent:
    image: amir20/dozzle:latest
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007