services:
  hyper-hdr:
    container_name: hyper-hdr
    hostname: hyper-hdr
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HYPERHDR_VERSION: "21.0.0.0"  # Replace with the desired version
        ARCH: "aarch64"               # Replace with the appropriate architecture (e.g., armhf, arm64, amd64) - `uname -m` helps
    network_mode: host
    privileged: true                  # Not recommended, but mounting the correct devices out of those 10+ is also ugly
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000

    volumes:
      - ./config:/config
    restart: unless-stopped
    
  dozzle-agent:
    image: amir20/dozzle:latest
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007